import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {chromium} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {localStack,fixtures,sql,rows,quote,signedToken,api,rpc,totp} from '../admin-foundation/local-stack.mjs';
import {nextProbe} from '../admin-foundation/local-next-probe.mjs';
let stack,users,probe,browser,ownerClient,ownerToken,emptyCatalog,created=false;
const origin='http://localhost:3038',output=path.resolve('../../outputs/f74-browser');
const token=(name,options)=>signedToken(stack,users[name],options);
const claims=t=>JSON.parse(Buffer.from(t.split('.')[1],'base64url'));
const tx=(query,t=token('admin'))=>sql('begin;select set_config(\'request.jwt.claims\','+quote(JSON.stringify(claims(t)))+',true);'+query+';commit;');
const createPayload=(patch={})=>({type_key:'local_fixture',config_version:1,slug:'fixture-'+randomUUID(),title:'Local campaign',configuration:{count:1},...patch});
const create=(payload=createPayload(),t=token('admin'))=>rpc(stack,'admin_campaign_create',t,{payload});
const row=id=>rows('select * from private.campaigns where id='+quote(id))[0];
const audit=id=>rows('select * from private.admin_audit_log where campaign_id='+quote(id)+' order by resulting_version');
const core=id=>{const r=row(id);return Object.fromEntries(['slug','title','visibility','scheduled_public_display','archived_history_display','config_version','configuration'].map(k=>[k,r[k]]));};
const update=(id,payload=core(id),version=row(id).version,t=token('admin'))=>rpc(stack,'admin_campaign_update',t,{target_campaign:id,expected_version:version,payload});
const detail=(id,t=token('staff'))=>rpc(stack,'admin_campaign_detail',t,{target_campaign:id});
const windows=id=>Object.fromEntries(['registration_opens_at','registration_closes_at','event_starts_at','event_ends_at'].map(k=>[k,row(id)[k]]));
async function fresh(patch={}){const result=await create(createPayload(patch));assert.equal(result.status,200);return result.data.id;}
function stateFixture(status='draft',closes='null') {const id=randomUUID();tx(`insert into private.campaigns(id,type_key,slug,title,status,configuration,registration_opens_at,registration_closes_at) values (${quote(id)},'local_fixture',${quote('fixture-'+id)},'Browser campaign',${quote(status)},'{"count":1}',${status==='scheduled'?"clock_timestamp()-interval '1 hour'":'null'},${closes})`);return id;}
async function unchanged(id,operation,status){const r=row(id),events=audit(id);assert.equal((await operation()).status,status);assert.deepEqual(row(id),r);assert.deepEqual(audit(id),events);}
async function ownerSession(){ownerClient=createClient(stack.url,stack.anon,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const link=await api(stack,'/auth/v1/admin/generate_link',{service:true,method:'POST',body:{type:'magiclink',email:users.owner.email}});assert.equal(link.status,200);const result=await api(stack,'/auth/v1/verify',{method:'POST',body:{token_hash:link.data.hashed_token,type:'magiclink'}});assert.equal(result.status,200);users.owner.session=claims(result.data.access_token).session_id;sql(`insert into auth.mfa_amr_claims(id,session_id,created_at,updated_at,authentication_method) values (${quote(randomUUID())},${quote(users.owner.session)},now(),now(),'oauth')`);assert.equal((await ownerClient.auth.setSession({access_token:result.data.access_token,refresh_token:result.data.refresh_token})).error,null);assert.equal((await ownerClient.auth.refreshSession()).error,null);const factor=await ownerClient.auth.mfa.enroll({factorType:'totp',friendlyName:'Local management verification'});assert.equal(factor.error,null);const resultMfa=await ownerClient.auth.mfa.challengeAndVerify({factorId:factor.data.id,code:totp(factor.data.totp.secret)});assert.equal(resultMfa.error,null);ownerToken=resultMfa.data.access_token;}
function cookie(t){const c=claims(t),session={access_token:t,refresh_token:'synthetic-local-no-refresh',token_type:'bearer',expires_in:3600,expires_at:c.exp,user:{id:c.sub,email:c.email}};return 'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url');}
async function pageFor(name='admin',viewport={width:1280,height:900}){const context=await browser.newContext({viewport});const t=name==='owner-fresh'?ownerToken:token(name);await context.addCookies([{name:'sb-127-auth-token',value:cookie(t),url:origin+'/admin',sameSite:'Lax'}]);const page=await context.newPage();return {page,context};}
async function request(route,{t=token('admin'),body,headers={},method='POST'}={}){const response=await fetch(origin+route,{method,redirect:'manual',headers:{Cookie:'sb-127-auth-token='+cookie(t),Origin:origin,'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)}),signal:AbortSignal.timeout(15000)});return {status:response.status,headers:response.headers,text:await response.text()};}
const lastVersions=()=>sql('select count(*)||\':\'||coalesce(sum(version),0) from private.campaigns')+':'+sql('select count(*) from private.admin_audit_log');
before(async()=>{stack=localStack();users=fixtures();created=true;await ownerSession();emptyCatalog=await rpc(stack,'admin_campaign_types',token('staff'));
  sql(`create function private.local_fixture_management(data jsonb) returns boolean language sql immutable set search_path='' as $$ select jsonb_typeof(data)='object' and data ? 'count' and (select count(*) from jsonb_object_keys(data))=1 and jsonb_typeof(data->'count')='number' and (data->>'count') ~ '^[1-9][0-9]{0,3}$' $$;
    revoke all on function private.local_fixture_management(jsonb) from public,anon,authenticated,service_role,supabase_auth_admin,authenticator;
    insert into private.campaign_type_descriptors values ('local_fixture',1,'local_fixture.enabled','local_fixture_management'),('local_fixture',2,'local_fixture.enabled','local_fixture_management');`);
  probe=await nextProbe(stack);browser=await chromium.launch({channel:'msedge',headless:true});mkdirSync(output,{recursive:true});
});
after(async()=>{await browser?.close();await probe?.close();await ownerClient?.auth.stopAutoRefresh();if(created){execFileSync(process.execPath,['scripts/admin-foundation/local-cli.mjs','db','reset','--local','--no-seed'],{stdio:'pipe'});for(const name of ['private.campaign_type_descriptors','private.campaigns','private.system_feature_flags','private.admin_audit_log','private.admin_invites','public.admin_profiles','auth.users'])assert.equal(sql('select count(*) from '+name),'0');assert.equal(sql("select count(*) from pg_proc where proname like 'local_fixture%'"),'0');assert.equal(sql("select count(*) from pg_roles where rolname like 'local_fixture%'"),'0');assert.equal(sql("select rolcanlogin from pg_roles where rolname='campaign_scheduler'"),'f');}});
test('real local empty production catalog and deliberate production UI empty state',async()=>{assert.equal(emptyCatalog.status,200);assert.deepEqual(emptyCatalog.data,[]);const {page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns');await page.getByRole('heading',{name:'Belum ada kempen',exact:true}).waitFor();await page.goto(origin+'/admin/campaigns/new');await page.getByText('Belum ada jenis kempen yang tersedia.').waitFor();assert.equal(await page.locator('input,textarea,select').count(),0);assert.equal(await page.getByRole('link',{name:'Kempen',exact:true}).count(),1);await page.screenshot({path:path.join(output,'empty-desktop.png'),fullPage:true});}finally{await context.close();}});
test('catalog returns only type/version/module and never validator metadata',async()=>{const r=await rpc(stack,'admin_campaign_types',token('admin'));assert.equal(r.status,200);assert.equal(r.data.length,2);for(const d of r.data)assert.deepEqual(Object.keys(d).sort(),['config_version','module_flag_key','type_key']);assert(!JSON.stringify(r.data).includes('validator'));});
test('create DB defaults, version, actor and one exact atomic audit',async()=>{const id=await fresh(),r=row(id),events=audit(id);assert.equal(r.status,'draft');assert.equal(r.visibility,'private');assert.equal(r.version,1);assert.equal(r.scheduled_public_display,false);assert.equal(r.archived_history_display,false);assert(Object.values(windows(id)).every(v=>v===null));assert.equal(r.created_by,users.admin.id);assert.equal(r.updated_by,users.admin.id);assert.equal(events.length,1);assert.equal(events[0].action,'campaign.create');assert.equal(events[0].actor_id,users.admin.id);assert.equal(events[0].expected_version,0);assert.equal(events[0].resulting_version,1);assert.deepEqual(events[0].metadata,{config_version:1,visibility:'private',to_status:'draft'});});
for(const [label,patch] of [ ['unknown type',{type_key:'unknown_fixture'}],['absent version',{config_version:3}],['invalid version',{config_version:'not-a-number'}],['invalid configuration',{configuration:{count:0}}],['oversized configuration',{configuration:{count:1,data:'x'.repeat(4097)}}],['reserved slug',{slug:'admin'}],['uppercase slug',{slug:'UPPER-fixture'}],['padded title',{title:' title '}],['actor override',{actor_id:'override'}],['status override',{status:'open'}],['version override',{version:4}],['window override',{registration_opens_at:'2027-01-01T00:00:00Z'}],['visibility override',{visibility:'public'}]])test('DB create rejects '+label,async()=>{const before=lastVersions();assert.equal((await create(createPayload(patch))).status,400);assert.equal(lastVersions(),before);});
test('duplicate normalized slug denied without extra audit',async()=>{const payload=createPayload();await create(payload);const before=lastVersions();assert.equal((await create(payload)).status,409);assert.equal(lastVersions(),before);});
for(const name of [null,'outsider','disabled','revoked','staff','owner'])test('DB read/write membership boundary '+(name??'anon'),async()=>{const id=await fresh(),t=name?token(name):null;const denied=name?403:401;assert.equal((await create(createPayload(),t)).status,denied);await unchanged(id,()=>update(id,core(id),1,t),denied);if(name!=='staff'){assert.equal((await detail(id,t)).status,denied);assert.equal((await rpc(stack,'admin_campaign_types',t)).status,denied);}else assert.equal((await detail(id,t)).status,200);});
test('real Auth-issued owner TOTP permits management; signed stale evidence cannot',async()=>{assert.equal(claims(ownerToken).aal,'aal2');const id=(await create(createPayload(),ownerToken)).data.id;assert(id);assert.equal((await update(id,{...core(id),title:'Owner change'},1,ownerToken)).status,200);const stale=token('owner',{aal:'aal2',amr:[{method:'oauth',timestamp:Math.floor(Date.now()/1000)},{method:'totp',timestamp:Math.floor(Date.now()/1000)-601}]});await unchanged(id,()=>update(id,core(id),2,stale),403);});
test('staff metadata forgery cannot become manager/owner/scheduler',async()=>{const t=token('staff',{metadata:{role:'super_admin',actor_category:'scheduler'}}),id=await fresh();assert.equal((await create(createPayload(),t)).status,403);await unchanged(id,()=>update(id,core(id),1,t),403);});
test('private tables/schema and internal helper RPC bypass remain denied',async()=>{for(const endpoint of ['/rest/v1/campaigns','/rest/v1/system_feature_flags'])for(const method of ['GET','POST','PATCH','DELETE'])assert.notEqual((await api(stack,endpoint,{token:token('admin'),method,...(method==='GET'?{}:{body:{title:'Override'}})})).status,200);assert.equal((await api(stack,'/rest/v1/campaigns',{token:token('admin'),headers:{'Accept-Profile':'private'}})).status,406);assert.equal((await rpc(stack,'campaign_management_create',token('admin'),{payload:createPayload()})).status,404);});
test('ACL: exact authenticated guarded boundary, invoker wrappers, trusted owner and empty search paths',()=>{const guarded=['private.campaign_type_catalog()','private.campaign_management_detail(uuid)','private.campaign_management_create(jsonb)','private.campaign_management_update(uuid,integer,jsonb)','public.admin_campaign_types()','public.admin_campaign_detail(uuid)','public.admin_campaign_create(jsonb)','public.admin_campaign_update(uuid,integer,jsonb)'];const internal=['private.campaign_management_payload(jsonb,boolean,text)','private.campaign_management_projection(private.campaigns)'];for(const sig of [...guarded,...internal]){const f=rows('select prosecdef,proconfig,pg_get_userbyid(proowner) owner from pg_proc where oid='+quote(sig)+'::regprocedure')[0];assert.equal(f.owner,'postgres');assert(f.proconfig.includes('search_path=""'));if(sig.startsWith('public.'))assert.equal(f.prosecdef,false);for(const role of ['anon','service_role','supabase_auth_admin','authenticator','campaign_scheduler'])assert.equal(sql('select has_function_privilege('+quote(role)+','+quote(sig)+",'EXECUTE')"),'f');assert.equal(sql("select has_function_privilege('authenticated',"+quote(sig)+",'EXECUTE')"),guarded.includes(sig)?'t':'f');}for(const privilege of ['SELECT','INSERT','UPDATE','DELETE'])assert.equal(sql("select has_table_privilege('authenticated','private.campaigns',"+quote(privilege)+')'),'f');});
test('safe detail unknown UUID/null handling and no actor leakage',async()=>{const id=await fresh();const r=await detail(id);assert.equal(r.status,200);assert.equal(r.data.id,id);assert.equal(r.data.slug_editable,true);for(const key of ['created_by','updated_by','validator_name','actor_category'])assert(!Object.hasOwn(r.data,key));assert.deepEqual((await detail(randomUUID())).data,null);assert.equal((await detail(null)).status,400);});
test('safe bounded list has no config or profile/validator internals',async()=>{for(let i=0;i<52;i++)await fresh();const r=await rpc(stack,'campaign_foundation_list',token('staff'),{page_size:50});assert.equal(r.status,200);assert.equal(r.data.length,50);for(const c of r.data)for(const key of ['configuration','created_by','updated_by','validator_name'])assert(!Object.hasOwn(c,key));});
for(const [field,value] of [['title','Changed title'],['slug','fixture-'+randomUUID()],['visibility','unlisted'],['scheduled_public_display',true],['archived_history_display',true],['configuration',{count:2}],['config_version',2]])test('DB update exact changed_fields '+field,async()=>{const id=await fresh(),prior=row(id);const r=await update(id,{...core(id),[field]:value});assert.equal(r.status,200);assert.equal(r.data.version,2);assert.equal(row(id).status,prior.status);assert.deepEqual(windows(id),{registration_opens_at:null,registration_closes_at:null,event_starts_at:null,event_ends_at:null});assert.deepEqual(audit(id)[1].metadata.changed_fields,[field]);assert.equal(audit(id)[1].action,'campaign.update');assert.equal(audit(id)[1].expected_version,1);assert.equal(audit(id)[1].resulting_version,2);});
test('identical current-version no-op and stale identical update 409 have no extra audit',async()=>{const id=await fresh();const no=await update(id);assert.equal(no.status,200);assert.equal(no.data.changed,false);assert.equal(row(id).version,1);assert.equal(audit(id).length,1);await update(id,{...core(id),title:'New title'});await unchanged(id,()=>update(id,core(id),1),409);});
for(const key of ['type_key','status','registration_opens_at','actor_id','updated_by','version'])test('DB update rejects extra '+key,async()=>{const id=await fresh();await unchanged(id,()=>update(id,{...core(id),[key]:'override'}),400);});
test('unsupported update config version/shape cannot discard original configuration',async()=>{const id=await fresh();for(const patch of [{config_version:3},{configuration:{}},{configuration:{count:1,unexpected:true}},{visibility:'invalid'},{scheduled_public_display:'true'}])await unchanged(id,()=>update(id,{...core(id),...patch}),400);});
test('slug sealed by lifecycle remains locked after unschedule',async()=>{const id=await fresh();let r=await rpc(stack,'admin_campaign_schedule',token('admin'),{target_campaign:id,expected_version:1,windows:{...windows(id),registration_opens_at:new Date(Date.now()+3600000).toISOString()}});assert.equal(r.status,200);r=await rpc(stack,'admin_campaign_lifecycle',token('admin'),{target_campaign:id,expected_version:2,command_action:'schedule'});assert.equal(r.status,200);assert.equal((await detail(id)).data.slug_editable,false);assert.equal((await rpc(stack,'admin_campaign_lifecycle',token('admin'),{target_campaign:id,expected_version:3,command_action:'unschedule'})).status,200);assert.equal(row(id).status,'draft');await unchanged(id,()=>update(id,{...core(id),slug:'fixture-'+randomUUID()},4),400);});
test('two distinct managers same expected version: one write/audit, other conflict',async()=>{const id=await fresh(),payload=core(id);const r=await Promise.all([update(id,{...payload,title:'First'},1),update(id,{...payload,title:'Second'},1,ownerToken)]);assert.deepEqual(r.map(v=>v.status).sort(),[200,409]);assert.equal(row(id).version,2);assert.equal(audit(id).length,2);assert.equal(audit(id)[1].actor_id,r[0].status===200?users.admin.id:users.owner.id);});
test('create/update audit failure rolls back entire mutation',async()=>{sql("create function private.local_fixture_audit_failure() returns trigger language plpgsql set search_path='' as $$ begin if new.action in ('campaign.create','campaign.update') then raise exception 'Test audit failure';end if;return new;end $$;create trigger local_fixture_management_audit before insert on private.admin_audit_log for each row execute function private.local_fixture_audit_failure();");try{const before=lastVersions();assert.equal((await create()).status,400);assert.equal(lastVersions(),before);}finally{sql('drop trigger local_fixture_management_audit on private.admin_audit_log;');}const id=await fresh();sql('create trigger local_fixture_management_audit before insert on private.admin_audit_log for each row execute function private.local_fixture_audit_failure();');try{await unchanged(id,()=>update(id,{...core(id),title:'Rollback'}),400);}finally{sql('drop trigger local_fixture_management_audit on private.admin_audit_log;drop function private.local_fixture_audit_failure();');}});
test('Foundation/flag governance is still owner-only and audit remains append-only',async()=>{for(const name of ['admin','staff']){assert.equal((await rpc(stack,'admin_owner_snapshot',token(name))).status,403);assert.equal((await rpc(stack,'admin_set_system_flag',token(name),{target_key:'campaigns.enabled',desired_enabled:true,expected_version:0})).status,403);}assert.throws(()=>sql("update private.admin_audit_log set action='recovery'"),/append|immutable|denied/i);assert.throws(()=>sql('delete from private.admin_audit_log'),/append|immutable|denied/i);});
test('safe audit projection excludes Foundation/flag families; staff denied',async()=>{const id=await fresh();const r=await rpc(stack,'campaign_audit_history',token('admin'),{target_campaign:id,page_size:50});assert.equal(r.status,200);assert.equal(r.data.length,1);assert(r.data.every(a=>a.campaign_id===id&&a.flag_key===null));assert.equal((await rpc(stack,'campaign_audit_history',token('staff'),{target_campaign:id,page_size:50})).status,403);});
for(const [label,headers,body,status] of [['missing Origin',{Origin:''},'{}',403],['foreign Origin',{Origin:'https://foreign.invalid'},'{}',403],['cross-site',{'Sec-Fetch-Site':'cross-site'},'{}',403],['non-JSON',{'Content-Type':'text/plain'},'{}',422],['malformed JSON',{},'{',422],['oversized normal',{},'x'.repeat(8193),422],['oversized multibyte',{},'é'.repeat(4097),422]])test('real Next create/update HTTP '+label,async()=>{const id=await fresh(),before=lastVersions();for(const route of ['/admin/api/campaigns','/admin/api/campaigns/'+id]){const r=await request(route,{headers,body});assert.equal(r.status,status);assert.match(r.headers.get('cache-control'),/no-store/);assert(!r.text.includes('SQL'));}assert.equal(lastVersions(),before);});
test('real chunked body overflow rejected with no mutation; Next upstream EOF boundary explicit',async()=>{const id=await fresh(),before=lastVersions();for(const route of ['/admin/api/campaigns','/admin/api/campaigns/'+id]){let pulls=0;const body=new ReadableStream({pull(c){c.enqueue(new TextEncoder().encode('x'.repeat(4096)));if(++pulls===3)c.close();}});const response=await fetch(origin+route,{method:'POST',duplex:'half',headers:{Cookie:'sb-127-auth-token='+cookie(token('admin')),Origin:origin,'Content-Type':'application/json'},body});assert.equal(response.status,422);}assert.equal(lastVersions(),before);});
test('real same-origin command respects empty app registry; arbitrary fields/query/method denied',async()=>{const id=await fresh(),before=lastVersions();assert.equal((await request('/admin/api/campaigns',{body:createPayload()})).status,422);assert.equal((await request('/admin/api/campaigns/'+id,{body:{expectedVersion:1,...core(id)}})).status,422);assert.equal((await request('/admin/api/campaigns?actor=owner',{body:createPayload()})).status,422);assert.equal((await request('/admin/api/campaigns/'+id,{method:'PATCH',body:{status:'open'}})).status,405);assert.equal(lastVersions(),before);await update(id,{...core(id),title:'HTTP conflict setup'},1);const changed=lastVersions();assert.equal((await request('/admin/api/campaigns/'+id,{body:{expectedVersion:1,...core(id)}})).status,409);assert.equal(lastVersions(),changed);});
test('real Next anonymous campaign pages redirect; authenticated outsider/inactive APIs deny',async()=>{const id=await fresh();for(const route of ['/admin/campaigns','/admin/campaigns/new','/admin/campaigns/'+id]){const r=await probe.request(route);assert([303,307].includes(r.status));assert.match(r.headers.get('location'),/\/admin\/login/);}for(const route of ['/admin/api/campaigns','/admin/api/campaigns/'+id]){assert.equal((await probe.request(route)).status,401);for(const name of ['outsider','disabled','revoked'])assert.equal((await probe.request(route,{token:token(name)})).status,403);}assert.equal((await probe.request('/admin/api/campaigns',{method:'POST',body:createPayload()})).status,401);});
test('real Next staff mutations denied while manager lifecycle remains accepted',async()=>{const id=await fresh(),before=lastVersions();const bodies={'':{expectedVersion:1,...core(id)},'/lifecycle':{action:'open',expectedVersion:1},'/schedule':{expectedVersion:1,...windows(id)}};for(const [suffix,body] of Object.entries(bodies))assert.equal((await request('/admin/api/campaigns/'+id+suffix,{t:token('staff'),body})).status,403);assert.equal((await request('/admin/api/campaigns',{t:token('staff'),body:createPayload()})).status,403);assert.equal(lastVersions(),before);assert.equal((await request('/admin/api/campaigns/'+id+'/lifecycle',{body:{action:'open',expectedVersion:1}})).status,200);});
test('real Next owner stale/no-MFA cannot mutate; safe fresh GET and unknown UUID return 404',async()=>{const id=await fresh();for(const t of [token('owner'),token('owner',{aal:'aal2',amr:[{method:'oauth',timestamp:Math.floor(Date.now()/1000)},{method:'totp',timestamp:Math.floor(Date.now()/1000)-601}]})])assert.equal((await request('/admin/api/campaigns/'+id+'/lifecycle',{t,body:{action:'open',expectedVersion:1}})).status,403);const r=await probe.request('/admin/api/campaigns/'+id,{token:token('staff')});assert.equal(r.status,200);const data=JSON.parse(r.text);assert.equal(data.audit,null);assert.equal(data.canManage,false);assert(!r.text.includes(users.admin.id));assert.equal((await probe.request('/admin/api/campaigns/'+randomUUID(),{token:token('admin')})).status,404);});
test('browser staff reads detail with no forms/lifecycle/audit and no unavailable config fallback',async()=>{const id=await fresh(),{page,context}=await pageFor('staff');try{await page.goto(origin+'/admin/campaigns/'+id);await page.getByText('Akses staff: baca sahaja.').waitFor();assert.equal(await page.locator('form').count(),0);assert.equal(await page.getByRole('heading',{name:'Sejarah aktiviti'}).count(),0);assert.equal(await page.getByRole('button',{name:'Buka kempen',exact:true}).count(),0);assert.equal(await page.locator('textarea').count(),0);await page.goto(origin+'/admin/campaigns/new');assert.equal(await page.locator('form').count(),0);}finally{await context.close();}});
test('browser real conflict blocks retry, preserves unsaved windows, explicit reload gets version',async()=>{const id=await fresh(),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);const input=page.locator('[name=event_starts_at]');await input.fill('2027-02-01T08:00');assert.equal((await update(id,{...core(id),title:'Concurrent manager change'},1)).status,200);let posts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/schedule'))posts++;});await page.getByRole('button',{name:'Simpan jadual',exact:true}).click();await page.getByText('Kempen ini telah berubah sejak halaman dibuka. Muat semula data terkini sebelum cuba lagi.').waitFor();assert.equal(posts,1);assert.equal(await page.getByRole('button',{name:'Simpan jadual',exact:true}).isDisabled(),true);assert.equal(await input.inputValue(),'2027-02-01T08:00');await page.getByRole('button',{name:'Muat semula data terkini',exact:true}).click();await page.getByText('Data terkini dimuatkan.',{exact:false}).waitFor();assert.equal(await input.inputValue(),'2027-02-01T08:00');assert.equal(row(id).version,2);assert.equal(posts,1);await page.getByRole('button',{name:'Simpan jadual',exact:true}).click();await page.getByText('Perubahan disahkan.',{exact:false}).waitFor();assert.equal(row(id).version,3);assert.equal(new Date(row(id).event_starts_at).toISOString(),'2027-02-01T00:00:00.000Z');}finally{await context.close();}});
test('browser lifecycle conflict never automatically retries destructive command',async()=>{const id=stateFixture('open'),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);await page.getByRole('button',{name:'Tutup kempen',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByText('Kempen yang ditutup tidak boleh dibuka semula.',{exact:false}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Batal'}).evaluate(e=>e===document.activeElement),true);await update(id,{...core(id),title:'Concurrent title'},1);let count=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/lifecycle'))count++;});await dialog.getByRole('button',{name:'Sahkan tindakan'}).click();await page.getByText('Kempen ini telah berubah sejak halaman dibuka.',{exact:false}).waitFor();assert.equal(row(id).status,'open');assert.equal(count,1);await page.getByRole('button',{name:'Muat semula data terkini'}).click();await page.getByText('Data terkini dimuatkan.',{exact:false}).waitFor();assert.equal(count,1);assert.equal(row(id).status,'open');}finally{await context.close();}});
test('browser confirmed lifecycle chain updates canonical state/version/audit through reused API',async()=>{const id=await fresh(),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);let version=1;for(const [label,state,action] of [['Buka kempen','open','open'],['Jeda kempen','paused','pause'],['Sambung kempen','open','resume'],['Tutup kempen','closed','close'],['Arkibkan','archived','archive']]){await page.getByRole('button',{name:label,exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/lifecycle')&&r.request().method()==='POST');await page.getByRole('dialog').getByRole('button',{name:'Sahkan tindakan'}).click();assert.equal((await response).status(),200);await page.getByText('Perubahan disahkan.',{exact:false}).waitFor();assert.equal(row(id).status,state);assert.equal(row(id).version,++version);assert.equal(audit(id).at(-1).action,'lifecycle.'+action);}assert.equal(await page.getByRole('button',{name:'Buka kempen',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Simpan jadual',exact:true}).count(),0);}finally{await context.close();}});
test('browser schedule cannot rescue persisted expired deadline; audit uses only original close',async()=>{const id=stateFixture('open',"clock_timestamp()-interval '1 minute'"),prior=row(id),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);await page.locator('[name=registration_closes_at]').fill('2027-12-31T23:00');await page.getByRole('button',{name:'Simpan jadual'}).click();await page.getByText('Perubahan disahkan.',{exact:false}).waitFor();const r=row(id);assert.equal(r.status,'closed');assert.equal(r.registration_closes_at,prior.registration_closes_at);assert.equal(r.version,2);assert.equal(audit(id).length,1);assert.equal(audit(id)[0].action,'lifecycle.close');assert.equal(audit(id)[0].metadata.cause,'schedule_edit_deadline');assert.equal(new Date(audit(id)[0].metadata.planned_at).getTime(),new Date(prior.registration_closes_at).getTime());assert.equal(await page.getByRole('button',{name:'Simpan jadual'}).count(),0);}finally{await context.close();}});
test('browser future extension before deadline works and remains lifecycle-neutral',async()=>{const id=stateFixture('paused',"clock_timestamp()+interval '1 hour'"),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);await page.locator('[name=registration_closes_at]').fill('2027-12-31T23:00');await page.getByRole('button',{name:'Simpan jadual'}).click();await page.getByText('Perubahan disahkan.',{exact:false}).waitFor();assert.equal(row(id).status,'paused');assert.equal(audit(id)[0].action,'schedule.change');assert.equal(sql('select count(*) from private.system_feature_flags'),'0');}finally{await context.close();}});
const actionNames={draft:['Jadualkan','Buka kempen','Arkibkan'],scheduled:['Batalkan penjadualan','Buka kempen','Tutup kempen'],open:['Jeda kempen','Tutup kempen'],paused:['Sambung kempen','Tutup kempen'],closed:['Arkibkan'],archived:[]};
for(const [status,actions] of Object.entries(actionNames))test('browser exact action set '+status,async()=>{const id=stateFixture(status),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);for(const name of new Set(Object.values(actionNames).flat()))assert.equal(await page.getByRole('button',{name,exact:true}).count(),actions.includes(name)?1:0);assert.equal(await page.locator('select[name=status]').count(),0);if(status==='draft'){await page.getByRole('button',{name:'Buka kempen',exact:true}).click();await page.getByRole('dialog').getByText('Meninggalkan draf mengunci slug secara kekal.',{exact:false}).waitFor();await page.keyboard.press('Escape');assert.equal(row(id).status,'draft');}if(status==='closed'){await page.getByRole('button',{name:'Arkibkan',exact:true}).click();await page.getByRole('dialog').getByText('Arkib ialah status akhir.',{exact:false}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Batal'}).click();}}finally{await context.close();}});
test('browser admin safe history never displays Foundation/security/flag internals',async()=>{const id=await fresh(),{page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns/'+id);await page.getByRole('heading',{name:'Sejarah aktiviti'}).waitFor();await page.getByText('Kempen dicipta',{exact:true}).waitFor();const text=await page.locator('main').innerText();assert(!text.includes(users.admin.id));assert(!text.includes('bootstrap'));assert(!text.includes('system_flag'));assert(!text.includes('secret'));assert.equal(await page.locator('textarea').count(),0);}finally{await context.close();}});
test('responsive desktop/tablet/mobile, labelled forms, focus and real screenshots',async()=>{const id=await fresh();for(const width of [1440,768,390]){const {page,context}=await pageFor('admin',{width,height:900});try{await page.goto(origin+'/admin/campaigns/'+id);await page.getByRole('heading',{name:'Jadual',exact:true}).waitFor();assert.equal(await page.locator('input').evaluateAll(inputs=>inputs.every(i=>i.labels?.length>0)),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('[name=event_starts_at]').focus();const outline=await page.locator('[name=event_starts_at]').evaluate(e=>getComputedStyle(e).outlineStyle);assert.notEqual(outline,'none');await page.screenshot({path:path.join(output,'detail-'+width+'.png'),fullPage:true});}finally{await context.close();}}});
test('DB outage is 503/unavailable, never an empty campaign list',async()=>{sql('alter table private.campaigns rename to local_fixture_hidden_campaigns');try{const r=await probe.request('/admin/api/campaigns',{token:token('admin')});assert.equal(r.status,503);const {page,context}=await pageFor();try{await page.goto(origin+'/admin/campaigns');await page.getByRole('heading',{name:'Data operasi tidak tersedia'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Belum ada kempen',exact:true}).count(),0);}finally{await context.close();}}finally{sql('alter table private.local_fixture_hidden_campaigns rename to campaigns');}});
