import assert from "node:assert/strict";
import crypto from "node:crypto";
import path from "node:path";
import { createRequire } from "node:module";
import { createClient } from "@sanity/client";
import { createJiti } from "jiti";
import { ROOT } from "../sanity-migration/plan.mjs";
import { validatePlan } from "../sanity-migration/validation.mjs";
createRequire(import.meta.url)("@next/env").loadEnvConfig(ROOT);
const jiti = createJiti(import.meta.url, { fsCache: false, moduleCache: true });
const load = file => jiti.import(path.join(ROOT,file));
const { projectId, dataset, apiVersion } = await load("src/sanity/env.ts");
assert.equal(projectId,"2o95jmms"); assert.equal(dataset,"production");
const q = await load("src/lib/public-content/lectures/queries.ts");
const c = await load("src/lib/public-content/lectures/content.ts");
const { stableJson } = await load("src/sanity/tools/lecture-generator/month-document.ts");
const client = createClient({ projectId,dataset,apiVersion,perspective:"published",token:undefined,useCdn:false,timeout:15000,maxRetries:0 });
const index = c.mapLectureIndex(await client.fetch(q.lectureIndexQuery));
assert.deepEqual(index.map(m=>m.key),["2026-10"]);
const result = await client.fetch(q.lectureMonthQuery,{id:"lectureMonth-2026-10"});
const month = c.mapLectureMonth(result,"2026-10");
// Reuse compiled Studio schema validation for this existing published document;
// this is a current-state check, not a rewrite of any historical migration plan.
const validation = await validatePlan({ assets:[],errors:[],collisions:[],missing:[] }, [result.document], client);
assert.deepEqual(validation.errors, []); assert.deepEqual(validation.warnings, []);
const { _id,_rev,_createdAt,_updatedAt,...content } = result.document;
void _id; void _createdAt; void _updatedAt;
const fingerprint = crypto.createHash("sha256").update(stableJson(content)).digest("hex");
assert.equal(_rev,"zVZDfWLj75qTdy5eh9rsNA");
assert.equal(fingerprint,"d18eb8c75642d32065fe509e9ba5f219a7d68c5989c7fc6cf4b538cb5fa547b6");
assert.equal(month.schedule.entries.length,30);
assert.equal(month.schedule.entries.reduce((n,e)=>n+e.sessions.length,0),34);
const references = new Set(month.schedule.entries.flatMap(e=>e.sessions.flatMap(s=>s.photo?[s.photo.cmsImage.asset._ref]:[])));
assert.equal(references.size,29); assert.equal(month.showInfaq,true); assert.ok(month.compactQr);
const text = JSON.stringify(month.schedule);
for(const exact of ["AL-QUR’AN","UST K. NI’MAT","UST MUHD MU’IZZ","KITAB MATLA’","Potret UST K. NI’MAT","Potret UST MUHD MU’IZZ"]) assert.ok(text.includes(exact));
console.log(JSON.stringify({mode:"READ-ONLY-PUBLISHED-LECTURE-CONTRACT",target:{projectId,dataset},publishedMonths:index.length,revision:_rev,dates:30,sessions:34,resolvedPortraitAssets:references.size,compactQr:month.compactQr.assetId,fingerprint,schema:validation,unicode:"exact",drafts:"Not observable through token-free published reads",writes:0},null,2));
